# Site wide configuration
title: Philip Van de Vyver - Azure Blog
description: 'A blog with a focus on Microsoft Azure'
url: https://blog.philipvandevyver.com
date_format: '%B %d, %Y'
fort_awesome_icon: 'cloud'

# Owner configuration
# name and email are required (change code to remove these)
# (leave the rest blank to disable the corresponding sharing button)
owner:
    name: Philip Van de Vyver
    email: philip.vandevyver@2forward.be
    github: pvyver
    twitter: pvyver
    linkedin: philipvandevyver
    facebook:
    google_plus:
    youtube:

# Post sharing icons
sharing:
    twitter: true
    linkedin: true
    facebook: true
    google_plus: true
    reddit: true

# Disqus comments configuration (leave blank to disable comments)
disqus_shortname: 'philipvandevyver'

# Jekyll configuration
permalink: /:year/:month/:day/:title/
paginate: 5

# Markdown
markdown: redcarpet
highlighter: rouge

# Enable when using redcarpet
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data', 'footnotes']

# Enable when using kramdown (you will need to use ~~~ instead of ```)
# kramdown:
#   auto_ids: true
#   footnote_nr: 1
#   entity_output: as_char
#   toc_levels: 1..6
#   use_coderay: false

# Gems
gems: ['jekyll-paginate']

# Exclude
exclude: ['README.md']

include:
  - "_images"